export type AnswerOption =
  | 'Normal'
  | 'Dry'
  | 'Oily'
  | 'Combination'
  | 'Sensitive'
  | 'Dark spot & Pigmentation'
  | 'Acne & Breakouts'
  | 'Blemishes & Sensitive'
  | 'Hydrating'
  | 'Anti-aging & Wrinkles'
  | 'Pores'
